# Use the official image as a parent image
FROM mcr.microsoft.com/vscode/devcontainers/python:3.7

# Install any additional dependencies here

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog
